ToDoList/Models/TodoList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ToDoList.Models
{
    public partial class TodoList
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [StringLength(500)]
        public string Description { get; set; }

        public bool IsComplete { get; set; }

        public PriorityLevel Priority { get; set; }
    }

    public enum PriorityLevel {
        None = 0,
        Low = 1,
        Medium = 2,
        High = 3
    }
}

ToDoList/Controllers/ToDoController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoList.Interface;
using ToDoList.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ToDoList.Controllers
{
    [Controller]
    public class ToDoController : Controller
    {
        private readonly IToDoRepository _repo;

        public ToDoController(IToDoRepository repo)
        {
            _repo = repo;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var items = await _repo.Get();

            return View(items);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var info = await _repo.Details(id);

            if (info == null)
            {
                return NotFound();
            }

            return View(info);
        }
        
        // GET /todo/create
        public IActionResult Post() => View();

        // POST /todo/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Post(
            [Bind("Name,Priority")] TodoList item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _repo.Post(item);

                    if (item == null)
                    {
                        throw new ArgumentNullException(nameof(item));
                    }
                }
            }
            catch (DbUpdateException ex)
            {
                ModelState.AddModelError("", "Unable to save changes. " + ex);
            }
            
            return View(item);
        }

        // GET /todo/edit/5
        public async Task<IActionResult> Update(int id)
        {
            // Receiving the specific item
            TodoList item = await _repo.GetById(id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);

        }

        // PUT /todo/edit/5
        [HttpPut]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(TodoList item)
        {
            if (ModelState.IsValid)
            {
                await _repo.Update(item);

                TempData["Success"] = "The item has been updated!";

                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET /todo/delete/5
        public async Task<IActionResult> Delete(int id)
        {
            // Receiving the specific item
            TodoList item = await _repo.Delete(id);

            if (item == null)
            {
                TempData["Error"] = "The item does not exist!";
            }
            else
            {
                TempData["Success"] = "The item has been deleted!";
            }

            return RedirectToAction("Index");
        }
    }
}

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="ToDo" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["Success"] != null)
            {
                <div class="alert alert-success">
                    @TempData["Success"]
                </div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="alert alert-danger">
                    @TempData["Error"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ToDoList/Views/ToDo/Create.cshtml
@model ToDoList.Models.TodoList

@{
    ViewData["Title"] = "Create";
}

<h1>Create a new task</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" valuta="Post" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoList/Views/ToDo/Details.cshtml
@model ToDoList.Models.TodoList

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Task detail</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Update" asp-route-id="@Model.Id">Edit</a>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoList/Views/ToDo/Edit.cshtml
@model ToDoList.Models.TodoList
    

@{
    ViewData["Title"] = "Edit";
}

<h1>Update</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to list</a>
</div>

ToDoList/Views/ToDo/Index.cshtml
@model IEnumerable<ToDoList.Models.TodoList> 

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Post">Create a new task</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Done
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    <form asp-action="MarkDone" method="post">
                        <input type="checkbox" class="done-checkbox" />
                        <input type="hidden" name="id" value="@item.Id" />
                    </form>
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ToDoList/Views/ToDo/Post.cshtml
@model ToDoList.Models.TodoList

@{
    ViewData["Title"] = "Post";
}

<h1>Create a new task</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <select asp-for="Priority" asp-items="Html.GetEnumSelectList<PriorityLevel>()" class="form-control">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" valuta="Post" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoList/Views/ToDo/Update.cshtml
@model ToDoList.Models.TodoList

@{
    ViewData["Title"] = "Edit";
}

<h1>Update</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to list</a>
</div>